version: "3.9"
services: 
  web:
    build: 
      context: .
      dockerfile: restart-on-failure.Dockerfile
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/db_talleresmcqueen
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root3434
    restart: on-failure
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root3434
      - MYSQL_DATABASE=db_talleresmcqueen
    volumes:
      - ./mysql:/var/lib/mysql