version: '3'
services:
  db: 
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root3434
      - MYSQL_DATABASE=db_talleresmcqueen
  
  web1:
    build: TalleresMCQueen/.
    expose:
      - "8443"
    restart: unless-stopped
    environment:
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/db_talleresmcqueen
      - APP_SERVICIO_REST=loadbalancer   

  web2:
    build: TalleresMCQueen/.
    expose:
      - "8443"
    restart: unless-stopped
    environment:
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/db_talleresmcqueen
      - APP_SERVICIO_REST=loadbalancer   

  broker:
    image: rabbitmq

  rabbitmq:
    build: InternalService/.
    environment:
      - SPRING_RABBITMQ_HOST=broker    
      - SPRING_MAIL_USERNAME=
      - SPRING_MAIL_PASSWORD=

  loadbalancer:
    image: haproxy:2.7.3
    ports:
     - "443:443"
     - "8282:8282"
    volumes:
     - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    restart: unless-stopped
